export interface BookType {
  createdAt?: Date;
  updatedAt?: Date;
  id?: number;
  libraryId?: string;
  barcode?: string;
  rentalStatus: string;
  rentedDate: Date | string;
  dueDate?: Date | string;
  renewalCount: number;
  title: string;
  subtitle?: string;
  author: string;
  topics?: string;
  imageLink?: string;
  isbn?: string;
  editionDescription?: string;
  publisherLocation?: string;
  pages?: number;
  summary?: string;
  publisherName?: string;
  otherPhysicalAttributes?: string;
  supplierComment?: string;
  publisherDate?: string;
  physicalSize?: string;
  minAge?: string;
  maxAge?: string;
  additionalMaterial?: string;
  price?: string;
  externalLinks?: string;
  userId?: number;
  user?: { firstName?: string; lastName?: string };
}
