export const xlsbookcolumns = [
  { key: 'id', header: 'ID' },
  { key: 'createdAt', header: 'Създадена на' },
  { key: 'updatedAt', header: 'Актуализиран на' },
  { key: 'barcode', header: 'Баркод' },
  { key: 'libraryId', header: 'Каталожен номер' },
  { key: 'rentalStatus', header: 'Статус' },
  { key: 'rentedDate', header: 'Взета на' },
  { key: 'dueDate', header: 'Взета до' },
  { key: 'renewalCount', header: 'Брой подновявания' },
  { key: 'title', header: 'Заглавие' },
  { key: 'subtitle', header: 'Подзаглавие' },
  { key: 'author', header: 'Автор' },
  { key: 'isbn', header: 'ISBN' },
  { key: 'editionDescription', header: 'Издание' },
  { key: 'publisherLocation', header: 'Държава на издаване' },
  { key: 'pages', header: 'Страници' },
  { key: 'summary', header: 'Резюме' },
  { key: 'publisherName', header: 'Издател' },
  { key: 'otherPhysicalAttributes', header: 'Други характеристики' },
  { key: 'supplierComment', header: 'Доставчик' },
  { key: 'publisherDate', header: 'Дата на публикуване' },
  { key: 'physicalSize', header: 'Размери' },
  { key: 'minAge', header: 'Мин възраст' },
  { key: 'maxAge', header: 'Макс възраст' },
  { key: 'userId', header: 'Взета от' },
];

export const xlsusercolumns = [
  { key: 'id', header: 'ID' },
  { key: 'createdAt', header: 'Създаден на' },
  { key: 'updatedAt', header: 'Актуализиран на' },
  { key: 'firstName', header: 'Име' },
  { key: 'lastName', header: 'Фамилия' },
  { key: 'eMail', header: 'Имейл' },
  { key: 'phone', header: 'Телефон' },
  { key: 'active', header: 'Активен' },
];
