export const xlsbookcolumns = [
  { key: 'id', header: 'Медиен номер' },
  { key: 'createdAt', header: 'Създаден на' },
  { key: 'updatedAt', header: 'Актуализиран на' },
  { key: 'rentalStatus', header: 'Статус на заемане' },
  { key: 'rentedDate', header: 'Зает на' },
  { key: 'dueDate', header: 'Връщане на' },
  { key: 'renewalCount', header: 'Брой подновявания' },
  { key: 'title', header: 'Заглавие' },
  { key: 'subtitle', header: 'Подзаглавие' },
  { key: 'author', header: 'Автор' },
  { key: 'topics', header: 'Теми' },
  { key: 'imageLink', header: 'Изображение' },
  { key: 'isbn', header: 'ISBN' },
  { key: 'editionDescription', header: 'Издание' },
  { key: 'publisherLocation', header: 'Местоположение на издателя' },
  { key: 'pages', header: 'Страници' },
  { key: 'summary', header: 'Резюме' },
  { key: 'minPlayers', header: 'Мин. играчи' },
  { key: 'publisherName', header: 'Издател' },
  { key: 'otherPhysicalAttributes', header: 'Характеристики' },
  { key: 'supplierComment', header: 'Доставчик' },
  { key: 'publisherDate', header: 'Дата на публикуване' },
  { key: 'physicalSize', header: 'Размери' },
  { key: 'minAge', header: 'Мин. възраст' },
  { key: 'maxAge', header: 'Макс. възраст' },
  { key: 'additionalMaterial', header: 'Материали' },
  { key: 'price', header: 'Цена' },
  { key: 'externalLinks', header: 'Връзки' },
  { key: 'userId', header: 'Заето от' },
];

export const xlsusercolumns = [
  { key: 'createdAt', header: 'Създаден на' },
  { key: 'updatedAt', header: 'Актуализиран на' },
  { key: 'id', header: 'Номер' },
  { key: 'lastName', header: 'Фамилия' },
  { key: 'firstName', header: 'Име' },
  { key: 'schoolGrade', header: 'Клас' },
  { key: 'schoolTeacherName', header: 'Учител' },
  { key: 'active', header: 'Активиран' },
  { key: 'eMail', header: 'Имейл' },
];
